apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datastore-cache
  annotations:
    kubernetes.io/reclaimPolicy: Delete
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: standard
  resources:
    requests:
      storage: ${PVC_SIZE}
