apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: SQSInformer
metadata:
  labels:
    app.kubernetes.io/name: unstructured-data-controller
    app.kubernetes.io/managed-by: kustomize
  name: sqsinformer-sample
spec:
  queueURL: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/unstructured-s3-queue
