apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: DocumentProcessor
metadata:
  labels:
    app.kubernetes.io/name: unstructured-data-controller
    app.kubernetes.io/managed-by: kustomize
  name: documentprocessor-sample
spec:
  stageName: convert
  dependsOn:
    - name: crawl
  config:
    type: docling
    doclingConfig:
      from_formats: [docx, pptx, html, image, pdf, asciidoc, md, csv, xlsx]
      to_formats: [md]
      image_export_mode: embedded
      do_ocr: true
      ocr_preset: auto
      pdf_backend: docling_parse
      pipeline: standard
      table_mode: accurate
      table_cell_matching: true
      do_table_structure: true
      include_images: true
      images_scale: "2.0"
      abort_on_error: false
