apiVersion: v1
kind: Secret
metadata:
  name: unstructured-secret
type: Opaque
stringData:
  DOCLING_USER_KEY: ""
  SOURCE_AWS_REGION: us-east-1
  SOURCE_AWS_ACCESS_KEY_ID: LSIAQAAAAAAVNCBMPNSG
  SOURCE_AWS_SECRET_ACCESS_KEY: LSIAQAAAAAAVNCBMPNSG
  SOURCE_AWS_SESSION_TOKEN: LSIAQAAAAAAVNCBMPNSG
  SOURCE_AWS_ENDPOINT: http://localstack:4566
  DESTINATION_AWS_REGION: us-east-1
  DESTINATION_AWS_ACCESS_KEY_ID: LSIAQAAAAAAVNCBMPNSG
  DESTINATION_AWS_SECRET_ACCESS_KEY: LSIAQAAAAAAVNCBMPNSG
  DESTINATION_AWS_SESSION_TOKEN: LSIAQAAAAAAVNCBMPNSG
  DESTINATION_AWS_ENDPOINT: http://localstack:4566
  SNOWFLAKE_PRIVATE_KEY: ${SNOWFLAKE_PRIVATE_KEY}
  FILE_STORE_AWS_REGION: us-east-1
  FILE_STORE_AWS_ACCESS_KEY_ID: LSIAQAAAAAAVNCBMPNSG
  FILE_STORE_AWS_SECRET_ACCESS_KEY: LSIAQAAAAAAVNCBMPNSG
  FILE_STORE_AWS_SESSION_TOKEN: LSIAQAAAAAAVNCBMPNSG
  FILE_STORE_AWS_ENDPOINT: http://localstack:4566
  NOMIC_API_KEY: ""
  NOMIC_ENDPOINT: "url/v1/embeddings"
