//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChunksGenerator) DeepCopyInto(out *ChunksGenerator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChunksGenerator.
func (in *ChunksGenerator) DeepCopy() *ChunksGenerator {
	if in == nil {
		return nil
	}
	out := new(ChunksGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChunksGenerator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChunksGeneratorConfig) DeepCopyInto(out *ChunksGeneratorConfig) {
	*out = *in
	in.RecursiveCharacterSplitterConfig.DeepCopyInto(&out.RecursiveCharacterSplitterConfig)
	out.MarkdownSplitterConfig = in.MarkdownSplitterConfig
	in.TokenSplitterConfig.DeepCopyInto(&out.TokenSplitterConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChunksGeneratorConfig.
func (in *ChunksGeneratorConfig) DeepCopy() *ChunksGeneratorConfig {
	if in == nil {
		return nil
	}
	out := new(ChunksGeneratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChunksGeneratorList) DeepCopyInto(out *ChunksGeneratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChunksGenerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChunksGeneratorList.
func (in *ChunksGeneratorList) DeepCopy() *ChunksGeneratorList {
	if in == nil {
		return nil
	}
	out := new(ChunksGeneratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChunksGeneratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChunksGeneratorSpec) DeepCopyInto(out *ChunksGeneratorSpec) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]StageDependency, len(*in))
		copy(*out, *in)
	}
	in.ChunksGeneratorConfig.DeepCopyInto(&out.ChunksGeneratorConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChunksGeneratorSpec.
func (in *ChunksGeneratorSpec) DeepCopy() *ChunksGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(ChunksGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChunksGeneratorStatus) DeepCopyInto(out *ChunksGeneratorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppliedConfig != nil {
		in, out := &in.AppliedConfig, &out.AppliedConfig
		*out = new(ChunksGeneratorConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChunksGeneratorStatus.
func (in *ChunksGeneratorStatus) DeepCopy() *ChunksGeneratorStatus {
	if in == nil {
		return nil
	}
	out := new(ChunksGeneratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfig) DeepCopyInto(out *ControllerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfig.
func (in *ControllerConfig) DeepCopy() *ControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigList) DeepCopyInto(out *ControllerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControllerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigList.
func (in *ControllerConfigList) DeepCopy() *ControllerConfigList {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigSpec) DeepCopyInto(out *ControllerConfigSpec) {
	*out = *in
	if in.UnstructuredDataPipelineResyncInterval != nil {
		in, out := &in.UnstructuredDataPipelineResyncInterval, &out.UnstructuredDataPipelineResyncInterval
		*out = new(int)
		**out = **in
	}
	if in.GoogleDriveConfig != nil {
		in, out := &in.GoogleDriveConfig, &out.GoogleDriveConfig
		*out = new(GoogleDriveControllerConfig)
		**out = **in
	}
	if in.LDAPConfig != nil {
		in, out := &in.LDAPConfig, &out.LDAPConfig
		*out = new(LDAPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SnowflakeConfig != nil {
		in, out := &in.SnowflakeConfig, &out.SnowflakeConfig
		*out = new(SnowflakeConfig)
		**out = **in
	}
	if in.UnstructuredDataProcessingConfig != nil {
		in, out := &in.UnstructuredDataProcessingConfig, &out.UnstructuredDataProcessingConfig
		*out = new(UnstructuredDataProcessingConfigSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigSpec.
func (in *ControllerConfigSpec) DeepCopy() *ControllerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigStatus) DeepCopyInto(out *ControllerConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigStatus.
func (in *ControllerConfigStatus) DeepCopy() *ControllerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationSyncer) DeepCopyInto(out *DestinationSyncer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationSyncer.
func (in *DestinationSyncer) DeepCopy() *DestinationSyncer {
	if in == nil {
		return nil
	}
	out := new(DestinationSyncer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DestinationSyncer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationSyncerConfig) DeepCopyInto(out *DestinationSyncerConfig) {
	*out = *in
	out.S3DestinationConfig = in.S3DestinationConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationSyncerConfig.
func (in *DestinationSyncerConfig) DeepCopy() *DestinationSyncerConfig {
	if in == nil {
		return nil
	}
	out := new(DestinationSyncerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationSyncerList) DeepCopyInto(out *DestinationSyncerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DestinationSyncer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationSyncerList.
func (in *DestinationSyncerList) DeepCopy() *DestinationSyncerList {
	if in == nil {
		return nil
	}
	out := new(DestinationSyncerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DestinationSyncerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationSyncerSpec) DeepCopyInto(out *DestinationSyncerSpec) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]StageDependency, len(*in))
		copy(*out, *in)
	}
	out.DestinationSyncerConfig = in.DestinationSyncerConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationSyncerSpec.
func (in *DestinationSyncerSpec) DeepCopy() *DestinationSyncerSpec {
	if in == nil {
		return nil
	}
	out := new(DestinationSyncerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationSyncerStatus) DeepCopyInto(out *DestinationSyncerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationSyncerStatus.
func (in *DestinationSyncerStatus) DeepCopy() *DestinationSyncerStatus {
	if in == nil {
		return nil
	}
	out := new(DestinationSyncerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoclingConfig) DeepCopyInto(out *DoclingConfig) {
	*out = *in
	if in.FromFormats != nil {
		in, out := &in.FromFormats, &out.FromFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ToFormats != nil {
		in, out := &in.ToFormats, &out.ToFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OCRLang != nil {
		in, out := &in.OCRLang, &out.OCRLang
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TableCellMatching != nil {
		in, out := &in.TableCellMatching, &out.TableCellMatching
		*out = new(bool)
		**out = **in
	}
	if in.DoTableStructure != nil {
		in, out := &in.DoTableStructure, &out.DoTableStructure
		*out = new(bool)
		**out = **in
	}
	if in.IncludeImages != nil {
		in, out := &in.IncludeImages, &out.IncludeImages
		*out = new(bool)
		**out = **in
	}
	if in.PageRange != nil {
		in, out := &in.PageRange, &out.PageRange
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoclingConfig.
func (in *DoclingConfig) DeepCopy() *DoclingConfig {
	if in == nil {
		return nil
	}
	out := new(DoclingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentProcessor) DeepCopyInto(out *DocumentProcessor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentProcessor.
func (in *DocumentProcessor) DeepCopy() *DocumentProcessor {
	if in == nil {
		return nil
	}
	out := new(DocumentProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentProcessor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentProcessorConfig) DeepCopyInto(out *DocumentProcessorConfig) {
	*out = *in
	in.DoclingConfig.DeepCopyInto(&out.DoclingConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentProcessorConfig.
func (in *DocumentProcessorConfig) DeepCopy() *DocumentProcessorConfig {
	if in == nil {
		return nil
	}
	out := new(DocumentProcessorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentProcessorList) DeepCopyInto(out *DocumentProcessorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DocumentProcessor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentProcessorList.
func (in *DocumentProcessorList) DeepCopy() *DocumentProcessorList {
	if in == nil {
		return nil
	}
	out := new(DocumentProcessorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentProcessorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentProcessorSpec) DeepCopyInto(out *DocumentProcessorSpec) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]StageDependency, len(*in))
		copy(*out, *in)
	}
	in.DocumentProcessorConfig.DeepCopyInto(&out.DocumentProcessorConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentProcessorSpec.
func (in *DocumentProcessorSpec) DeepCopy() *DocumentProcessorSpec {
	if in == nil {
		return nil
	}
	out := new(DocumentProcessorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentProcessorStatus) DeepCopyInto(out *DocumentProcessorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]Job, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PermanentlyFailingFiles != nil {
		in, out := &in.PermanentlyFailingFiles, &out.PermanentlyFailingFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AppliedConfig != nil {
		in, out := &in.AppliedConfig, &out.AppliedConfig
		*out = new(DocumentProcessorConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentProcessorStatus.
func (in *DocumentProcessorStatus) DeepCopy() *DocumentProcessorStatus {
	if in == nil {
		return nil
	}
	out := new(DocumentProcessorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleDriveConfig) DeepCopyInto(out *GoogleDriveConfig) {
	*out = *in
	if in.Folders != nil {
		in, out := &in.Folders, &out.Folders
		*out = make([]GoogleDriveFolders, len(*in))
		copy(*out, *in)
	}
	if in.SkipFolders != nil {
		in, out := &in.SkipFolders, &out.SkipFolders
		*out = make([]SkipFolders, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleDriveConfig.
func (in *GoogleDriveConfig) DeepCopy() *GoogleDriveConfig {
	if in == nil {
		return nil
	}
	out := new(GoogleDriveConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleDriveControllerConfig) DeepCopyInto(out *GoogleDriveControllerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleDriveControllerConfig.
func (in *GoogleDriveControllerConfig) DeepCopy() *GoogleDriveControllerConfig {
	if in == nil {
		return nil
	}
	out := new(GoogleDriveControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleDriveFolders) DeepCopyInto(out *GoogleDriveFolders) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleDriveFolders.
func (in *GoogleDriveFolders) DeepCopy() *GoogleDriveFolders {
	if in == nil {
		return nil
	}
	out := new(GoogleDriveFolders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Job) DeepCopyInto(out *Job) {
	*out = *in
	in.DoclingConfig.DeepCopyInto(&out.DoclingConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Job.
func (in *Job) DeepCopy() *Job {
	if in == nil {
		return nil
	}
	out := new(Job)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPConfig) DeepCopyInto(out *LDAPConfig) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPConfig.
func (in *LDAPConfig) DeepCopy() *LDAPConfig {
	if in == nil {
		return nil
	}
	out := new(LDAPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarkdownSplitterConfig) DeepCopyInto(out *MarkdownSplitterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarkdownSplitterConfig.
func (in *MarkdownSplitterConfig) DeepCopy() *MarkdownSplitterConfig {
	if in == nil {
		return nil
	}
	out := new(MarkdownSplitterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NomicEmbedTextV15Config) DeepCopyInto(out *NomicEmbedTextV15Config) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NomicEmbedTextV15Config.
func (in *NomicEmbedTextV15Config) DeepCopy() *NomicEmbedTextV15Config {
	if in == nil {
		return nil
	}
	out := new(NomicEmbedTextV15Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineStage) DeepCopyInto(out *PipelineStage) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]StageDependency, len(*in))
		copy(*out, *in)
	}
	if in.SourceCrawlerConfig != nil {
		in, out := &in.SourceCrawlerConfig, &out.SourceCrawlerConfig
		*out = new(SourceCrawlerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DocumentProcessorConfig != nil {
		in, out := &in.DocumentProcessorConfig, &out.DocumentProcessorConfig
		*out = new(DocumentProcessorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ChunksGeneratorConfig != nil {
		in, out := &in.ChunksGeneratorConfig, &out.ChunksGeneratorConfig
		*out = new(ChunksGeneratorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.VectorEmbeddingsGeneratorConfig != nil {
		in, out := &in.VectorEmbeddingsGeneratorConfig, &out.VectorEmbeddingsGeneratorConfig
		*out = new(VectorEmbeddingsGeneratorConfig)
		**out = **in
	}
	if in.DestinationSyncerConfig != nil {
		in, out := &in.DestinationSyncerConfig, &out.DestinationSyncerConfig
		*out = new(DestinationSyncerConfig)
		**out = **in
	}
	if in.QueryConfig != nil {
		in, out := &in.QueryConfig, &out.QueryConfig
		*out = new(QueryConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineStage.
func (in *PipelineStage) DeepCopy() *PipelineStage {
	if in == nil {
		return nil
	}
	out := new(PipelineStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryConfig) DeepCopyInto(out *QueryConfig) {
	*out = *in
	if in.Snowflake != nil {
		in, out := &in.Snowflake, &out.Snowflake
		*out = new(SnowflakeQueryConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryConfig.
func (in *QueryConfig) DeepCopy() *QueryConfig {
	if in == nil {
		return nil
	}
	out := new(QueryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecursiveCharacterSplitterConfig) DeepCopyInto(out *RecursiveCharacterSplitterConfig) {
	*out = *in
	if in.Separators != nil {
		in, out := &in.Separators, &out.Separators
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecursiveCharacterSplitterConfig.
func (in *RecursiveCharacterSplitterConfig) DeepCopy() *RecursiveCharacterSplitterConfig {
	if in == nil {
		return nil
	}
	out := new(RecursiveCharacterSplitterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Config) DeepCopyInto(out *S3Config) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Config.
func (in *S3Config) DeepCopy() *S3Config {
	if in == nil {
		return nil
	}
	out := new(S3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkipFolders) DeepCopyInto(out *SkipFolders) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkipFolders.
func (in *SkipFolders) DeepCopy() *SkipFolders {
	if in == nil {
		return nil
	}
	out := new(SkipFolders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeConfig) DeepCopyInto(out *SnowflakeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeConfig.
func (in *SnowflakeConfig) DeepCopy() *SnowflakeConfig {
	if in == nil {
		return nil
	}
	out := new(SnowflakeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeQueryConfig) DeepCopyInto(out *SnowflakeQueryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeQueryConfig.
func (in *SnowflakeQueryConfig) DeepCopy() *SnowflakeQueryConfig {
	if in == nil {
		return nil
	}
	out := new(SnowflakeQueryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceCrawler) DeepCopyInto(out *SourceCrawler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceCrawler.
func (in *SourceCrawler) DeepCopy() *SourceCrawler {
	if in == nil {
		return nil
	}
	out := new(SourceCrawler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceCrawler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceCrawlerConfig) DeepCopyInto(out *SourceCrawlerConfig) {
	*out = *in
	out.S3Config = in.S3Config
	if in.GoogleDriveConfig != nil {
		in, out := &in.GoogleDriveConfig, &out.GoogleDriveConfig
		*out = new(GoogleDriveConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceCrawlerConfig.
func (in *SourceCrawlerConfig) DeepCopy() *SourceCrawlerConfig {
	if in == nil {
		return nil
	}
	out := new(SourceCrawlerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceCrawlerList) DeepCopyInto(out *SourceCrawlerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SourceCrawler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceCrawlerList.
func (in *SourceCrawlerList) DeepCopy() *SourceCrawlerList {
	if in == nil {
		return nil
	}
	out := new(SourceCrawlerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceCrawlerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceCrawlerSpec) DeepCopyInto(out *SourceCrawlerSpec) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]StageDependency, len(*in))
		copy(*out, *in)
	}
	in.SourceCrawlerConfig.DeepCopyInto(&out.SourceCrawlerConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceCrawlerSpec.
func (in *SourceCrawlerSpec) DeepCopy() *SourceCrawlerSpec {
	if in == nil {
		return nil
	}
	out := new(SourceCrawlerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceCrawlerStatus) DeepCopyInto(out *SourceCrawlerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceCrawlerStatus.
func (in *SourceCrawlerStatus) DeepCopy() *SourceCrawlerStatus {
	if in == nil {
		return nil
	}
	out := new(SourceCrawlerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageCreationStatus) DeepCopyInto(out *StageCreationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageCreationStatus.
func (in *StageCreationStatus) DeepCopy() *StageCreationStatus {
	if in == nil {
		return nil
	}
	out := new(StageCreationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageDependency) DeepCopyInto(out *StageDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageDependency.
func (in *StageDependency) DeepCopy() *StageDependency {
	if in == nil {
		return nil
	}
	out := new(StageDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenSplitterConfig) DeepCopyInto(out *TokenSplitterConfig) {
	*out = *in
	if in.AllowedSpecial != nil {
		in, out := &in.AllowedSpecial, &out.AllowedSpecial
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisallowedSpecial != nil {
		in, out := &in.DisallowedSpecial, &out.DisallowedSpecial
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenSplitterConfig.
func (in *TokenSplitterConfig) DeepCopy() *TokenSplitterConfig {
	if in == nil {
		return nil
	}
	out := new(TokenSplitterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredDataPipeline) DeepCopyInto(out *UnstructuredDataPipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredDataPipeline.
func (in *UnstructuredDataPipeline) DeepCopy() *UnstructuredDataPipeline {
	if in == nil {
		return nil
	}
	out := new(UnstructuredDataPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnstructuredDataPipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredDataPipelineList) DeepCopyInto(out *UnstructuredDataPipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnstructuredDataPipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredDataPipelineList.
func (in *UnstructuredDataPipelineList) DeepCopy() *UnstructuredDataPipelineList {
	if in == nil {
		return nil
	}
	out := new(UnstructuredDataPipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnstructuredDataPipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredDataPipelineSpec) DeepCopyInto(out *UnstructuredDataPipelineSpec) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]PipelineStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredDataPipelineSpec.
func (in *UnstructuredDataPipelineSpec) DeepCopy() *UnstructuredDataPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(UnstructuredDataPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredDataPipelineStatus) DeepCopyInto(out *UnstructuredDataPipelineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]StageCreationStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredDataPipelineStatus.
func (in *UnstructuredDataPipelineStatus) DeepCopy() *UnstructuredDataPipelineStatus {
	if in == nil {
		return nil
	}
	out := new(UnstructuredDataPipelineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredDataProcessingConfigSpec) DeepCopyInto(out *UnstructuredDataProcessingConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredDataProcessingConfigSpec.
func (in *UnstructuredDataProcessingConfigSpec) DeepCopy() *UnstructuredDataProcessingConfigSpec {
	if in == nil {
		return nil
	}
	out := new(UnstructuredDataProcessingConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorEmbeddingsGenerator) DeepCopyInto(out *VectorEmbeddingsGenerator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorEmbeddingsGenerator.
func (in *VectorEmbeddingsGenerator) DeepCopy() *VectorEmbeddingsGenerator {
	if in == nil {
		return nil
	}
	out := new(VectorEmbeddingsGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VectorEmbeddingsGenerator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorEmbeddingsGeneratorConfig) DeepCopyInto(out *VectorEmbeddingsGeneratorConfig) {
	*out = *in
	out.NomicEmbedTextV15Config = in.NomicEmbedTextV15Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorEmbeddingsGeneratorConfig.
func (in *VectorEmbeddingsGeneratorConfig) DeepCopy() *VectorEmbeddingsGeneratorConfig {
	if in == nil {
		return nil
	}
	out := new(VectorEmbeddingsGeneratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorEmbeddingsGeneratorList) DeepCopyInto(out *VectorEmbeddingsGeneratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VectorEmbeddingsGenerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorEmbeddingsGeneratorList.
func (in *VectorEmbeddingsGeneratorList) DeepCopy() *VectorEmbeddingsGeneratorList {
	if in == nil {
		return nil
	}
	out := new(VectorEmbeddingsGeneratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VectorEmbeddingsGeneratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorEmbeddingsGeneratorSpec) DeepCopyInto(out *VectorEmbeddingsGeneratorSpec) {
	*out = *in
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]StageDependency, len(*in))
		copy(*out, *in)
	}
	out.VectorEmbeddingsGeneratorConfig = in.VectorEmbeddingsGeneratorConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorEmbeddingsGeneratorSpec.
func (in *VectorEmbeddingsGeneratorSpec) DeepCopy() *VectorEmbeddingsGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(VectorEmbeddingsGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorEmbeddingsGeneratorStatus) DeepCopyInto(out *VectorEmbeddingsGeneratorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppliedConfig != nil {
		in, out := &in.AppliedConfig, &out.AppliedConfig
		*out = new(VectorEmbeddingsGeneratorConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorEmbeddingsGeneratorStatus.
func (in *VectorEmbeddingsGeneratorStatus) DeepCopy() *VectorEmbeddingsGeneratorStatus {
	if in == nil {
		return nil
	}
	out := new(VectorEmbeddingsGeneratorStatus)
	in.DeepCopyInto(out)
	return out
}
