//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChunksGeneratorConfig) DeepCopyInto(out *ChunksGeneratorConfig) {
	*out = *in
	in.RecursiveCharacterSplitterConfig.DeepCopyInto(&out.RecursiveCharacterSplitterConfig)
	out.MarkdownSplitterConfig = in.MarkdownSplitterConfig
	in.TokenSplitterConfig.DeepCopyInto(&out.TokenSplitterConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChunksGeneratorConfig.
func (in *ChunksGeneratorConfig) DeepCopy() *ChunksGeneratorConfig {
	if in == nil {
		return nil
	}
	out := new(ChunksGeneratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfig) DeepCopyInto(out *ControllerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfig.
func (in *ControllerConfig) DeepCopy() *ControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigList) DeepCopyInto(out *ControllerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControllerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigList.
func (in *ControllerConfigList) DeepCopy() *ControllerConfigList {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigSpec) DeepCopyInto(out *ControllerConfigSpec) {
	*out = *in
	out.UnstructuredDataProcessingConfig = in.UnstructuredDataProcessingConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigSpec.
func (in *ControllerConfigSpec) DeepCopy() *ControllerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigStatus) DeepCopyInto(out *ControllerConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigStatus.
func (in *ControllerConfigStatus) DeepCopy() *ControllerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationConfig) DeepCopyInto(out *DestinationConfig) {
	*out = *in
	out.SnowflakeInternalStageConfig = in.SnowflakeInternalStageConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationConfig.
func (in *DestinationConfig) DeepCopy() *DestinationConfig {
	if in == nil {
		return nil
	}
	out := new(DestinationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoclingConfig) DeepCopyInto(out *DoclingConfig) {
	*out = *in
	if in.FromFormats != nil {
		in, out := &in.FromFormats, &out.FromFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ToFormats != nil {
		in, out := &in.ToFormats, &out.ToFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OCRLang != nil {
		in, out := &in.OCRLang, &out.OCRLang
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoclingConfig.
func (in *DoclingConfig) DeepCopy() *DoclingConfig {
	if in == nil {
		return nil
	}
	out := new(DoclingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentProcessor) DeepCopyInto(out *DocumentProcessor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentProcessor.
func (in *DocumentProcessor) DeepCopy() *DocumentProcessor {
	if in == nil {
		return nil
	}
	out := new(DocumentProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentProcessor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentProcessorConfig) DeepCopyInto(out *DocumentProcessorConfig) {
	*out = *in
	in.DoclingConfig.DeepCopyInto(&out.DoclingConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentProcessorConfig.
func (in *DocumentProcessorConfig) DeepCopy() *DocumentProcessorConfig {
	if in == nil {
		return nil
	}
	out := new(DocumentProcessorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentProcessorList) DeepCopyInto(out *DocumentProcessorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DocumentProcessor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentProcessorList.
func (in *DocumentProcessorList) DeepCopy() *DocumentProcessorList {
	if in == nil {
		return nil
	}
	out := new(DocumentProcessorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentProcessorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentProcessorSpec) DeepCopyInto(out *DocumentProcessorSpec) {
	*out = *in
	in.DocumentProcessorConfig.DeepCopyInto(&out.DocumentProcessorConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentProcessorSpec.
func (in *DocumentProcessorSpec) DeepCopy() *DocumentProcessorSpec {
	if in == nil {
		return nil
	}
	out := new(DocumentProcessorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentProcessorStatus) DeepCopyInto(out *DocumentProcessorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Jobs != nil {
		in, out := &in.Jobs, &out.Jobs
		*out = make([]Job, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PermanentlyFailingFiles != nil {
		in, out := &in.PermanentlyFailingFiles, &out.PermanentlyFailingFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentProcessorStatus.
func (in *DocumentProcessorStatus) DeepCopy() *DocumentProcessorStatus {
	if in == nil {
		return nil
	}
	out := new(DocumentProcessorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Job) DeepCopyInto(out *Job) {
	*out = *in
	in.DoclingConfig.DeepCopyInto(&out.DoclingConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Job.
func (in *Job) DeepCopy() *Job {
	if in == nil {
		return nil
	}
	out := new(Job)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MarkdownSplitterConfig) DeepCopyInto(out *MarkdownSplitterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MarkdownSplitterConfig.
func (in *MarkdownSplitterConfig) DeepCopy() *MarkdownSplitterConfig {
	if in == nil {
		return nil
	}
	out := new(MarkdownSplitterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecursiveCharacterSplitterConfig) DeepCopyInto(out *RecursiveCharacterSplitterConfig) {
	*out = *in
	if in.Separators != nil {
		in, out := &in.Separators, &out.Separators
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecursiveCharacterSplitterConfig.
func (in *RecursiveCharacterSplitterConfig) DeepCopy() *RecursiveCharacterSplitterConfig {
	if in == nil {
		return nil
	}
	out := new(RecursiveCharacterSplitterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Config) DeepCopyInto(out *S3Config) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Config.
func (in *S3Config) DeepCopy() *S3Config {
	if in == nil {
		return nil
	}
	out := new(S3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQSConsumer) DeepCopyInto(out *SQSConsumer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQSConsumer.
func (in *SQSConsumer) DeepCopy() *SQSConsumer {
	if in == nil {
		return nil
	}
	out := new(SQSConsumer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SQSConsumer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQSConsumerList) DeepCopyInto(out *SQSConsumerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SQSConsumer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQSConsumerList.
func (in *SQSConsumerList) DeepCopy() *SQSConsumerList {
	if in == nil {
		return nil
	}
	out := new(SQSConsumerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SQSConsumerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQSConsumerSpec) DeepCopyInto(out *SQSConsumerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQSConsumerSpec.
func (in *SQSConsumerSpec) DeepCopy() *SQSConsumerSpec {
	if in == nil {
		return nil
	}
	out := new(SQSConsumerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQSConsumerStatus) DeepCopyInto(out *SQSConsumerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQSConsumerStatus.
func (in *SQSConsumerStatus) DeepCopy() *SQSConsumerStatus {
	if in == nil {
		return nil
	}
	out := new(SQSConsumerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeInternalStageConfig) DeepCopyInto(out *SnowflakeInternalStageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeInternalStageConfig.
func (in *SnowflakeInternalStageConfig) DeepCopy() *SnowflakeInternalStageConfig {
	if in == nil {
		return nil
	}
	out := new(SnowflakeInternalStageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceConfig) DeepCopyInto(out *SourceConfig) {
	*out = *in
	out.S3Config = in.S3Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceConfig.
func (in *SourceConfig) DeepCopy() *SourceConfig {
	if in == nil {
		return nil
	}
	out := new(SourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenSplitterConfig) DeepCopyInto(out *TokenSplitterConfig) {
	*out = *in
	if in.AllowedSpecial != nil {
		in, out := &in.AllowedSpecial, &out.AllowedSpecial
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisallowedSpecial != nil {
		in, out := &in.DisallowedSpecial, &out.DisallowedSpecial
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenSplitterConfig.
func (in *TokenSplitterConfig) DeepCopy() *TokenSplitterConfig {
	if in == nil {
		return nil
	}
	out := new(TokenSplitterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredDataProcessingConfigSpec) DeepCopyInto(out *UnstructuredDataProcessingConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredDataProcessingConfigSpec.
func (in *UnstructuredDataProcessingConfigSpec) DeepCopy() *UnstructuredDataProcessingConfigSpec {
	if in == nil {
		return nil
	}
	out := new(UnstructuredDataProcessingConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredDataProduct) DeepCopyInto(out *UnstructuredDataProduct) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredDataProduct.
func (in *UnstructuredDataProduct) DeepCopy() *UnstructuredDataProduct {
	if in == nil {
		return nil
	}
	out := new(UnstructuredDataProduct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnstructuredDataProduct) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredDataProductList) DeepCopyInto(out *UnstructuredDataProductList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnstructuredDataProduct, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredDataProductList.
func (in *UnstructuredDataProductList) DeepCopy() *UnstructuredDataProductList {
	if in == nil {
		return nil
	}
	out := new(UnstructuredDataProductList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnstructuredDataProductList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredDataProductSpec) DeepCopyInto(out *UnstructuredDataProductSpec) {
	*out = *in
	out.SourceConfig = in.SourceConfig
	out.DestinationConfig = in.DestinationConfig
	in.DocumentProcessorConfig.DeepCopyInto(&out.DocumentProcessorConfig)
	in.ChunksGeneratorConfig.DeepCopyInto(&out.ChunksGeneratorConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredDataProductSpec.
func (in *UnstructuredDataProductSpec) DeepCopy() *UnstructuredDataProductSpec {
	if in == nil {
		return nil
	}
	out := new(UnstructuredDataProductSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstructuredDataProductStatus) DeepCopyInto(out *UnstructuredDataProductStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstructuredDataProductStatus.
func (in *UnstructuredDataProductStatus) DeepCopy() *UnstructuredDataProductStatus {
	if in == nil {
		return nil
	}
	out := new(UnstructuredDataProductStatus)
	in.DeepCopyInto(out)
	return out
}
