nameSuffix: -test

namePrefix: unstructured-

namespace: unstructured-controller-namespace

resources:
- ../rbac
- ../manager

images:
- name: controller
  newName: localhost/unstructured-data-controller
  newTag: test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
