apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unstructured-controller-namespace

resources:
- serviceaccount.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- role.yaml
- rolebinding.yaml

images:
- name: mcp-server
  newName: ghcr.io/gshikhar2021/unstructured-data-controller-mcp-server
  newTag: testing
