name: Build

on:
  push:
    branches: [main, release-*]
    tags:
      - "v*"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches: [main, release-*]

jobs:
  build:
    name: Build Go Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        name: checkout the code
      - uses: actions/setup-go@v6
        name: setup go
        with:
          go-version-file: "go.mod"
          go-version: "1.25.x"
      - name: build
        run: |
          go build -v ./...
