name: Lint

on:
  push:
    branches: [main, release-*]
    tags:
      - "v*"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches: [main, release-*]

jobs:
  lint:
    name: GolangCILint and YAMLLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        name: checkout the code
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        name: setup go
        with:
          go-version-file: "go.mod"
          go-version: "1.26.x"
      - name: Install yamllint
        run: |
          pip install yamllint
      - name: fmt and vet
        run: |
          make fmt vet
      - name: lint
        run: |
          make lint
