name: E2E Tests

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches: [main]

jobs:
  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    environment: e2e-tests
    permissions:
      contents: read
      packages: read

    steps:
     - name: Print e2e tests
       run: |
         echo "Running E2E tests workflow"